export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const USER_AUTHENTICATION = 'USER_AUTHENTICATION';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_SERVICE_CATEGORIES = 'UPDATE_SERVICE_CATEGORIES';
